### ISSUE TITLE
Something wrong happend when i run 'manipulate.py' 

### ISSUE THREAD

**Issue by moon-landing** [genforce/higan#6]
沈博您好，我通过以下设置运行 manipulate.py：

LAYERS=6-11
python manipulate.py $MODEL_NAME $BOUNDARY_LIST \
    --num=10 \
    --layerwise_manipulation \
    --manipulate_layers=$LAYERS \
    --generate_html

在Colab上报错：
Log file `stylegan_bedroom_manipulation/log.txt` has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 09:53:49,930][WARNING] Overwriting log file `stylegan_bedroom_manipulation/log.txt`!
[2021-04-13 09:53:49,930][INFO] Initializing generator.
[2021-04-13 09:53:49,937][INFO] Build generator for model `stylegan_bedroom`.
[2021-04-13 09:53:50,190][INFO] Loading pytorch weights from `models/pretrain/pytorch/stylegan_bedroom256_generator.pth`.
[2021-04-13 09:53:50,534][INFO] Successfully loaded!
[2021-04-13 09:53:52,528][INFO] Current `lod` is 0.0.
[2021-04-13 09:53:52,528][INFO] Preparing latent codes.
[2021-04-13 09:53:52,528][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "manipulate.py", line 280, in <module>
    main()
  File "manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "/content/higan/utils/editor.py", line 383, in parse_boundary_list
    for line in f:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

问题出现在/utils/editor.py的383行:
 for line in f:
似乎是382行使用open函数无法正确打开boundary list的.npy文件：
with open(boundary_list_path, 'r') as f:

我已在colab和本地都进行了尝试，均在此处报错。
我也尝试修改open函数的encoding，也没有解决。

能否请您在百忙之中看一下我的问题，十分感谢！

 祝好！

**Comment by limbo0000** [comment]
Thanks for your testing. Could you please tell me which boundary you used? We will follow up then.

**Comment by moon-landing** [comment]
** I run 'manipulate.py' using Colab with following settings:**
LAYERS=6-11
MODEL_NAME=LAYERS=6-11
MODEL_NAME='stylegan_bedroom'
BOUNDARY_LIST='boundaries/stylegan_bedroom/carpet_boundary.npy'
!python manipulate.py $MODEL_NAME $BOUNDARY_LIST \
    --num=10 \
    --layerwise_manipulation \
    --manipulate_layers=$LAYERS \
    --generate_html

with the pretrained model 'models/pretrain/pytorch/stylegan_bedroom256_generator.pth'.
And I have downloaded Pre-trained predictors and put them in as the follows:

**Path:**
predictors
├  pretrain 
│  ├  W_sceneattribute_wideresnet18.npy
│  └  wideresnet18_places365.pth.tar
├  annotations
│  ├  categories_places365.txt
│  ├ labels_sunattribute.txt

**The feedback is as follows:**
Log file `stylegan_bedroom_manipulation/log.txt` has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 13:27:45,893][WARNING] Overwriting log file `stylegan_bedroom_manipulation/log.txt`!
[2021-04-13 13:27:45,893][INFO] Initializing generator.
[2021-04-13 13:27:45,917][INFO] Build generator for model `stylegan_bedroom`.
[2021-04-13 13:27:46,166][INFO] Loading pytorch weights from `models/pretrain/pytorch/stylegan_bedroom256_generator.pth`.
[2021-04-13 13:27:46,463][INFO] Successfully loaded!
[2021-04-13 13:27:48,569][INFO] Current `lod` is 0.0.
[2021-04-13 13:27:48,569][INFO] Preparing latent codes.
[2021-04-13 13:27:48,570][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "manipulate.py", line 280, in <module>
    main()
  File "manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "/content/higan/utils/editor.py", line 383, in parse_boundary_list
    for line in f:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

**In my own environment, I run 'manipulate.py' using pyCharm with following settings:**
stylegan_tower
boundaries/stylegan_tower/brick_boundary.npy
--num=10
--layerwise_manipulation
--manipulate_layers=6-10
--generate_html

with the pretrained model 'models/pretrain/tensorflow/stylegan_tower256_generator.pth'.
And I have downloaded Pre-trained predictors and put them in as the follows:

**Path:**
predictors
├  pretrain 
│  ├  W_sceneattribute_wideresnet18.npy
│  └  wideresnet18_places365.pth.tar
├  annotations
│  ├  categories_places365.txt
│  ├ labels_sunattribute.txt

**The feedback is as follows:**
C:\Users\ww\anaconda3\envs\pytorch\python.exe C:/code/higan-master/manipulate.py stylegan_tower boundaries/stylegan_tower/brick_boundary.npy --num=10 --layerwise_manipulation --manipulate_layers=6-10 --generate_html
Log file `stylegan_tower_manipulation\log.txt` has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 21:48:17,772][WARNING] Overwriting log file `stylegan_tower_manipulation\log.txt`!
[2021-04-13 21:48:17,773][INFO] Initializing generator.
[2021-04-13 21:48:17,796][INFO] Build generator for model `stylegan_tower`.
[2021-04-13 21:48:17,957][INFO] Loading pytorch weights from `models\pretrain\pytorch\stylegan_tower256_generator.pth`.
[2021-04-13 21:48:18,081][INFO] Successfully loaded!
[2021-04-13 21:48:20,038][INFO] Current `lod` is 0.0.
[2021-04-13 21:48:20,038][INFO] Preparing latent codes.
[2021-04-13 21:48:20,038][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "C:/code/higan-master/manipulate.py", line 280, in <module>
    main()
  File "C:/code/higan-master/manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "C:\code\higan-master\utils\editor.py", line 383, in parse_boundary_list
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 128: illegal multibyte sequence

Process finished with exit code 1



I didn't edit the code, and
In fact, whatever boundary I used can't be opened successfully. 
It seems that something wrong happened when decoding the boundary file.
I think it may be my own mistake, but I can't fix it well.

**Comment by moon-landing** [comment]
> Thanks for your testing. Could you please tell me which boundary you used? We will follow up then.

** I run 'manipulate.py' using Colab with following settings: **
LAYERS=6-11
MODEL_NAME=LAYERS=6-11
MODEL_NAME='stylegan_bedroom'
BOUNDARY_LIST='boundaries/stylegan_bedroom/carpet_boundary.npy'
!python manipulate.py $MODEL_NAME $BOUNDARY_LIST
--num=10
--layerwise_manipulation
--manipulate_layers=$LAYERS
--generate_html

with the pretrained model 'models/pretrain/pytorch/stylegan_bedroom256_generator.pth'.
And I have downloaded Pre-trained predictors and put them in as the follows:

Path:
predictors
├  pretrain
│  ├  W_sceneattribute_wideresnet18.npy
│  └  wideresnet18_places365.pth.tar
├  annotations
│  ├  categories_places365.txt
│  ├ labels_sunattribute.txt

The feedback is as follows:
Log file stylegan_bedroom_manipulation/log.txt has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 13:27:45,893][WARNING] Overwriting log file stylegan_bedroom_manipulation/log.txt!
[2021-04-13 13:27:45,893][INFO] Initializing generator.
[2021-04-13 13:27:45,917][INFO] Build generator for model stylegan_bedroom.
[2021-04-13 13:27:46,166][INFO] Loading pytorch weights from models/pretrain/pytorch/stylegan_bedroom256_generator.pth.
[2021-04-13 13:27:46,463][INFO] Successfully loaded!
[2021-04-13 13:27:48,569][INFO] Current lod is 0.0.
[2021-04-13 13:27:48,569][INFO] Preparing latent codes.
[2021-04-13 13:27:48,570][INFO] Sample latent codes randomly.
Traceback (most recent call last):
File "manipulate.py", line 280, in
main()
File "manipulate.py", line 171, in main
boundaries = parse_boundary_list(args.boundary_list_path)
File "/content/higan/utils/editor.py", line 383, in parse_boundary_list
for line in f:
File "/usr/lib/python3.7/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

In my own environment, I run 'manipulate.py' using pyCharm with following settings:
stylegan_tower
boundaries/stylegan_tower/brick_boundary.npy
--num=10
--layerwise_manipulation
--manipulate_layers=6-10
--generate_html

with the pretrained model 'models/pretrain/tensorflow/stylegan_tower256_generator.pth'.
And I have downloaded Pre-trained predictors and put them in as the follows:

Path:
predictors
├  pretrain
│  ├  W_sceneattribute_wideresnet18.npy
│  └  wideresnet18_places365.pth.tar
├  annotations
│  ├  categories_places365.txt
│  ├ labels_sunattribute.txt

The feedback is as follows:
C:\Users\ww\anaconda3\envs\pytorch\python.exe C:/code/higan-master/manipulate.py stylegan_tower boundaries/stylegan_tower/brick_boundary.npy --num=10 --layerwise_manipulation --manipulate_layers=6-10 --generate_html
Log file stylegan_tower_manipulation\log.txt has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 21:48:17,772][WARNING] Overwriting log file stylegan_tower_manipulation\log.txt!
[2021-04-13 21:48:17,773][INFO] Initializing generator.
[2021-04-13 21:48:17,796][INFO] Build generator for model stylegan_tower.
[2021-04-13 21:48:17,957][INFO] Loading pytorch weights from models\pretrain\pytorch\stylegan_tower256_generator.pth.
[2021-04-13 21:48:18,081][INFO] Successfully loaded!
[2021-04-13 21:48:20,038][INFO] Current lod is 0.0.
[2021-04-13 21:48:20,038][INFO] Preparing latent codes.
[2021-04-13 21:48:20,038][INFO] Sample latent codes randomly.
Traceback (most recent call last):
File "C:/code/higan-master/manipulate.py", line 280, in
main()
File "C:/code/higan-master/manipulate.py", line 171, in main
boundaries = parse_boundary_list(args.boundary_list_path)
File "C:\code\higan-master\utils\editor.py", line 383, in parse_boundary_list
for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 128: illegal multibyte sequence

Process finished with exit code 1

I didn't edit the code.
In fact, whatever boundary I used can't be opened successfully.
It seems that something wrong happened when decoding the boundary file using open() function.
I think it may be my own mistake, but I can't fix it well.

**Comment by moon-landing** [comment]
> Thanks for your testing. Could you please tell me which boundary you used? We will follow up then.


** I run 'manipulate.py' using Colab with following settings: **
LAYERS=6-11
MODEL_NAME=LAYERS=6-11
MODEL_NAME='stylegan_bedroom'
BOUNDARY_LIST='boundaries/stylegan_bedroom/carpet_boundary.npy'
!python manipulate.py $MODEL_NAME $BOUNDARY_LIST \
    --num=10 \
    --layerwise_manipulation \
    --manipulate_layers=$LAYERS \
    --generate_html

with the pretrained model 'models/pretrain/pytorch/stylegan_bedroom256_generator.pth'.
And I have downloaded Pre-trained predictors and put them in as the follows:

**Path:**
predictors
├  pretrain 
│  ├  W_sceneattribute_wideresnet18.npy
│  └  wideresnet18_places365.pth.tar
├  annotations
│  ├  categories_places365.txt
│  ├ labels_sunattribute.txt

**The feedback is as follows:**
Log file `stylegan_bedroom_manipulation/log.txt` has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 13:27:45,893][WARNING] Overwriting log file `stylegan_bedroom_manipulation/log.txt`!
[2021-04-13 13:27:45,893][INFO] Initializing generator.
[2021-04-13 13:27:45,917][INFO] Build generator for model `stylegan_bedroom`.
[2021-04-13 13:27:46,166][INFO] Loading pytorch weights from `models/pretrain/pytorch/stylegan_bedroom256_generator.pth`.
[2021-04-13 13:27:46,463][INFO] Successfully loaded!
[2021-04-13 13:27:48,569][INFO] Current `lod` is 0.0.
[2021-04-13 13:27:48,569][INFO] Preparing latent codes.
[2021-04-13 13:27:48,570][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "manipulate.py", line 280, in <module>
    main()
  File "manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "/content/higan/utils/editor.py", line 383, in parse_boundary_list
    for line in f:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

**In my own environment, I run 'manipulate.py' using pyCharm with following settings:**
stylegan_tower
boundaries/stylegan_tower/brick_boundary.npy
--num=10
--layerwise_manipulation
--manipulate_layers=6-10
--generate_html

with the pretrained model 'models/pretrain/tensorflow/stylegan_tower256_generator.pth'.
And I have downloaded Pre-trained predictors and put them in as the follows:

**Path:**
predictors
├  pretrain 
│  ├  W_sceneattribute_wideresnet18.npy
│  └  wideresnet18_places365.pth.tar
├  annotations
│  ├  categories_places365.txt
│  ├ labels_sunattribute.txt

**The feedback is as follows:**
C:\Users\ww\anaconda3\envs\pytorch\python.exe C:/code/higan-master/manipulate.py stylegan_tower boundaries/stylegan_tower/brick_boundary.npy --num=10 --layerwise_manipulation --manipulate_layers=6-10 --generate_html
Log file `stylegan_tower_manipulation\log.txt` has already existed!
Would you like to overwrite it (Y/N): Y
[2021-04-13 21:48:17,772][WARNING] Overwriting log file `stylegan_tower_manipulation\log.txt`!
[2021-04-13 21:48:17,773][INFO] Initializing generator.
[2021-04-13 21:48:17,796][INFO] Build generator for model `stylegan_tower`.
[2021-04-13 21:48:17,957][INFO] Loading pytorch weights from `models\pretrain\pytorch\stylegan_tower256_generator.pth`.
[2021-04-13 21:48:18,081][INFO] Successfully loaded!
[2021-04-13 21:48:20,038][INFO] Current `lod` is 0.0.
[2021-04-13 21:48:20,038][INFO] Preparing latent codes.
[2021-04-13 21:48:20,038][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "C:/code/higan-master/manipulate.py", line 280, in <module>
    main()
  File "C:/code/higan-master/manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "C:\code\higan-master\utils\editor.py", line 383, in parse_boundary_list
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 128: illegal multibyte sequence

Process finished with exit code 1



I didn't edit the code.
In fact, whatever boundary I used can't be opened successfully. 
It seems that something wrong happened when decoding the boundary file using open() function.
I think it may be my own mistake, but I can't fix it well.

**Comment by moon-landing** [comment]
Oh, It's my own mistake.
I forget to make a boundary list file.
I'm so sorry to waste your time.
