### ISSUE TITLE
decode errors in manipute.py

### ISSUE THREAD

**Issue by BeyondHeaven** [genforce/higan#8]
I got an error of decode. You can copy this code and paste it in [colab](https://colab.research.google.com/)
```
import os
os.chdir('/content')
CODE_DIR = 'higan'
!git clone https://github.com/genforce/higan.git $CODE_DIR
os.chdir(f'./{CODE_DIR}')
!python manipulate.py "stylegan_bedroom" "./boundaries/stylegan_bedroom/indoor_lighting_boundary.npy"  --num=10  --layerwise_manipulation  --manipulate_layers=6-11 --generate_html
```
The result is 

```
Cloning into 'higan'...
remote: Enumerating objects: 288, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 288 (delta 77), reused 263 (delta 58), pack-reused 0
Receiving objects: 100% (288/288), 16.22 MiB | 32.06 MiB/s, done.
Resolving deltas: 100% (77/77), done.
[2021-08-21 02:32:10,279][INFO] Initializing generator.
[2021-08-21 02:32:10,448][INFO] Build generator for model `stylegan_bedroom`.
[2021-08-21 02:32:10,822][WARNING] No pre-trained weights will be loaded!
[2021-08-21 02:32:10,829][INFO] Current `lod` is 0.0.
[2021-08-21 02:32:10,829][INFO] Preparing latent codes.
[2021-08-21 02:32:10,829][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "manipulate.py", line 280, in <module>
    main()
  File "manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "/content/higan/utils/editor.py", line 383, in parse_boundary_list
    for line in f:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```
I also test it on a local machine:
```
rd@rd-pc:/local/mnt/workspace/rd/code/higan$ /local/mnt/workspace/rd/anaconda3/bin/python manipulate.py $MODEL_NAME $BOUNDARY_LIST     --num=10     --layerwise_manipulation     --manipulate_layers=$LAYERS     --generate_html
Log file `stylegan_bedroom_manipulation/log.txt` has already existed!
Would you like to overwrite it (Y/N): y
[2021-08-21 09:41:46,172][WARNING] Overwriting log file `stylegan_bedroom_manipulation/log.txt`!
[2021-08-21 09:41:46,173][INFO] Initializing generator.
[2021-08-21 09:41:46,282][INFO] Build generator for model `stylegan_bedroom`.
[2021-08-21 09:41:46,488][INFO] Loading pytorch weights from `models/pretrain/pytorch/stylegan_bedroom256_generator.pth`.
[2021-08-21 09:41:46,600][INFO] Successfully loaded!
[2021-08-21 09:41:49,628][INFO] Current `lod` is 0.0.
[2021-08-21 09:41:49,629][INFO] Preparing latent codes.
[2021-08-21 09:41:49,629][INFO]   Sample latent codes randomly.
Traceback (most recent call last):
  File "manipulate.py", line 280, in <module>
    main()
  File "manipulate.py", line 171, in main
    boundaries = parse_boundary_list(args.boundary_list_path)
  File "/local/mnt/workspace/rd/code/higan/utils/editor.py", line 383, in parse_boundary_list
    for line in f:
  File "/local/mnt/workspace/rd/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```
Error occurs here: [] (https://github.com/genforce/higan/blob/2088e23cfd1e2ab86ce6eb4edf2abe1701cbb9d9/utils/editor.py#L383)

**Comment by BeyondHeaven** [comment]
this npy file can be opened by `np.load(path, allow_pickle=True).item()` but cannot be opened by `with open(boundary_list_path, 'r') as f:`

**Comment by BeyondHeaven** [comment]
Here is the content of `./boundaries/stylegan_bedroom/indoor_lighting_boundary.npy` 
```
{'boundary': array([[ 1.33193040e-02, -1.04234985e-01,  1.48448524e-02,
         4.14605010e-02,  1.47839572e-02,  1.79822394e-01,
        -5.08860698e-02, -7.00187776e-02,  1.89601951e-02,
        -2.21996300e-02,  2.49727761e-02,  4.02068307e-02,
        -2.83041915e-03, -5.11268689e-03, -7.28137567e-02,
         ...... 
         4.87090931e-02, -3.33814721e-02,  7.37967048e-02,
        -4.08401560e-02, -2.61659936e-03]]), 'meta_data': {'type': 'attribute', 'manipulate_layers': '6-11'}}
```
And this is the [parse function](https://github.com/genforce/higan/blob/2088e23cfd1e2ab86ce6eb4edf2abe1701cbb9d9/utils/editor.py#L386-L391)
```
      boundary_info, boundary_path = line.strip().split(':')
      boundary_name, space_type = boundary_info.strip()[1:-1].split(',')
      boundary_name = boundary_name.strip()
      space_type = space_type.strip().lower()
      boundary_path = boundary_path.strip()
      boundaries[(boundary_name, space_type)] = boundary_path
```
It seems that they are not match because there is no space_type or boundary_name. I think I make some mistakes about $BOUNDARY_LIST. What should this file be?

**Comment by BeyondHeaven** [comment]
I think I made the same mistake as this one:
https://github.com/genforce/higan/issues/6
